name = "german-lingo"
main = "dist/index.html"
compatibility_date = "2024-04-15"

[build]
command = "npm run build"

[site]
bucket = "./dist"
entry-point = "dist"

# Required for Pages
pages_build_output_dir = "dist"

[site.custom_domains]
domain = "germanlingo.com"
www = "www.germanlingo.com"
